# BASE UI
ColorColumn: 'gray darkgray b'
Conceal: 'darkgray'
Cursor: '- gray'
CursorIM: '@Cursor'
CursorColumn: '@CursorLine'
CursorLine: '- darkgray'
CursorLineNr: 'lightgreen darkgray'
Directory: 'green - b'
DiffAdd: 'green'
DiffChange: 'beige'
DiffDelete: 'red - b'
DiffText: 'white darkbeige'
ErrorMsg: 'magenta'
VertSplit: 'dark dark'
Folded: 'white gray'
FoldColumn: 'white gray'
SignColumn: 'white - b'
IncSearch: '- darkbeige'
LineNr: 'gray black'
MatchParen: '- gray'
ModeMsg: 'white'
MoreMsg: 'white'
NonText: 'darkgray'
Normal: 'white black'
PMenu: 'beige darkgray'
PMenuSel: 'black beige'
PmenuSbar: '@PMenuSel'
PmenuThumb: '@PMenuSel'
Question: 'white'
Search: 'darkgray beige'
SpecialKey: 'lightblue'
SpellBad: 'magenta - u'
SpellLocal: 'lightgreen - u'
SpellCap: 'lightblue - u'
SpellRare: 'lightgreen - u'
StatusLine: 'white darkgray'
StatusLineNC: 'black darkgray'
TabLine: 'black gray'
TabLineFill: 'gray'
TabLineSel: 'black gray b'
Title: 'green - b'
Visual: '- darkbeige'
VisualNOS: '@Visual'
WarningMsg: 'magenta'
WildMenu: '- gray'
# BASE SYNTAX
Comment: 'gray'
Constant: 'red'
String: 'beige' # Constant
Character: '' # Constant
Boolean: '' # Constant
Number: '' # Constant
Float: '' # Constant
Identifier: 'blue'
Function: 'lightgreen - b' # Identifier
Statement: 'green'
Conditional: '' # Statement
Repeat: '' # Statement
Label: '' # Statement
Operator: '' # Statement
Keyword: '' # Statement
Exception: '' # Statement
PreProc: 'lightgreen'
Include: '' # PreProc
Define: '' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: 'lightblue'
StorageClass: '' # Type
Structure: '' # Type
Typedef: '' # Type
Special: 'lightblue'
SpecialChar: '' # Special
Tag: '' # Special
Delimiter: '' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: 'lightblue - u'
Ignore: '@Conceal'
Error: 'magenta'
Todo: 'red - b'
